### ISSUE TITLE
Add support for PowerPC64 LE Linux

### ISSUE THREAD

**Issue by runlevel5** [rust-lang/rustc_codegen_cranelift#1482] opened 2024-04-17 06:59 UTC
The linux powerpc64le architecture has been quite popular amongst researchers and corporates. It would be great the architecture is supported. I could assist developers with access to ppc64le linux computers for development.

**Comment by bjorn3** [comment] 2024-04-17 07:30
Duplicate of https://github.com/rust-lang/rustc_codegen_cranelift/issues/1471. tl;dr: Cranelift needs to add a powerpc backend first.

**Closed by bjorn3** 2024-04-17 07:30 UTC

**Comment by bjorn3** [comment] 2024-04-17 07:32
Wait, you are the same person who opened that other issue. Why did you open another issue?

**Comment by runlevel5** [comment] 2024-04-17 09:09
>  Wait, you are the same person who opened that other issue. Why did you open another issue?

I am sorry for my poor mixing up. I did create one issue before.
