### ISSUE TITLE
cranelift fails to build Bevy 0.13.2 on macOS

### ISSUE THREAD

**Issue by janhohenheim** [rust-lang/rustc_codegen_cranelift#1504] opened 2024-07-04 13:33 UTC
`cargo --version`: `cargo 1.81.0-nightly (b1feb75d0 2024-06-07)`

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "cranelift-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
```

</details>
<details>
<summary>main.rs</summary>

```rust
fn main() {
    println!("Hello, world!");
}
```

</details>

<details>
<summary>~/.cargo/config.toml</summary>

```toml
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
```

</details>

System:
<img width="392" alt="image" src="https://github.com/rust-lang/rustc_codegen_cranelift/assets/9047632/c3cd676a-77b5-4952-9f0a-a289d05c5cbf">

Running `cargo build` results in the following:
```ignore
error: error writing object file: section name `__cstring,cstring_literals` is too long

error: could not compile `objc2` (lib) due to 1 previous error
```

**Comment by bjorn3** [comment] 2024-07-04 13:40
I'm currently splitting a `#[link_section = "__TEXT,__cstring,cstring_literals"]` at the first comma into segment name "__TEXT" and section name "__cstring,cstring_literals". Looks like I have to split additional commas to separate the section name, section type, (`+` separated) attributes and stub size: https://github.com/llvm/llvm-project/blob/main/llvm/lib/MC/MCSectionMachO.cpp

**Comment by bjorn3** [comment] 2024-07-04 19:21
I can reproduce this with Bevy 0.13.2 (both x86_64 and arm64) but not Bevy 0.14.0. I'm still going to fix it though.

**Comment by bjorn3** [comment] 2024-07-04 19:53
In particular objc2 version v0.3.0-beta.3.patch-leaks.3 gives the error. Mostly fixed in https://github.com/rust-lang/rustc_codegen_cranelift/commit/253436c04c87b7d8dfed2fb14e42a67427196bc1. https://github.com/bytecodealliance/wasmtime/issues/8901 is necessary for the being more technically correct.

**Comment by bjorn3** [comment] 2024-07-04 19:57
I just tried actually running the breakout example and it crashes...

**Comment by bjorn3** [comment] 2024-07-04 19:59
I've force pushed the previous commit away. I don't have time to investigate the crash right now.

**Comment by janhohenheim** [comment] 2024-07-04 20:02
I think if it works on Bevy 0.14, it's good enough to at least not block recommending cranelift to new users :)

**Comment by bjorn3** [comment] 2024-07-04 20:07
The crash happens with Bevy 0.14 too. That means the commit I force-pushed away is not at fault for this crash at least. I've pushed it again. Let's open a new issue for the crash though.

**Closed by bjorn3** 2024-07-04 20:07 UTC
Labels: C-bug, O-macos
